# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b351d2dc8c4608569918c6425a61b623225337aa550dfeb37e07435eae9fb56cacdeff4b4631cd66d07180ae1a7ecbcfc7374aa9ce964c53ab33f3a3373b450

test:
  secret_key_base: 59730c381ad9122dd7050873360ef27f595e160140fc83e41c6f0bb5ae70e0b3e1c3d29f6feb13a159d17e7989b043b8f0ccb69949f6df260016ed02b04c849b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
